apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<your-username>/kafka-gitops
    targetRevision: main
    path: helm/kafka-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

