apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: demo
  namespace: kafka
spec:
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

