apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: demo
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral

